// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package chunkstore

import ()

type Chunk struct {
	ID           []byte `db:"id"`
	LogicalLen   int64  `db:"logical_len"`
	StoredLen    int64  `db:"stored_len"`
	CompAlgo     int64  `db:"comp_algo"`
	CreatedNs    int64  `db:"created_ns"`
	LastAccessNs int64  `db:"last_access_ns"`
}
