// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package chunkstore

import (
	"context"
)

const chunkExists = `-- name: ChunkExists :one
SELECT 1 as exists_flag FROM chunks WHERE id = ?
`

func (q *Queries) ChunkExists(ctx context.Context, id []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, chunkExists, id)
	var exists_flag int64
	err := row.Scan(&exists_flag)
	return exists_flag, err
}

const deleteChunk = `-- name: DeleteChunk :exec
DELETE FROM chunks WHERE id = ?
`

func (q *Queries) DeleteChunk(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, deleteChunk, id)
	return err
}

const getChunkCompAlgo = `-- name: GetChunkCompAlgo :one
SELECT comp_algo FROM chunks WHERE id = ?
`

func (q *Queries) GetChunkCompAlgo(ctx context.Context, id []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChunkCompAlgo, id)
	var comp_algo int64
	err := row.Scan(&comp_algo)
	return comp_algo, err
}

const getChunkStat = `-- name: GetChunkStat :one
SELECT logical_len, stored_len FROM chunks WHERE id = ?
`

type GetChunkStatRow struct {
	LogicalLen int64 `db:"logical_len"`
	StoredLen  int64 `db:"stored_len"`
}

func (q *Queries) GetChunkStat(ctx context.Context, id []byte) (GetChunkStatRow, error) {
	row := q.db.QueryRowContext(ctx, getChunkStat, id)
	var i GetChunkStatRow
	err := row.Scan(&i.LogicalLen, &i.StoredLen)
	return i, err
}

const insertChunk = `-- name: InsertChunk :exec
INSERT INTO chunks (id, logical_len, stored_len, comp_algo, created_ns, last_access_ns) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertChunkParams struct {
	ID           []byte `db:"id"`
	LogicalLen   int64  `db:"logical_len"`
	StoredLen    int64  `db:"stored_len"`
	CompAlgo     int64  `db:"comp_algo"`
	CreatedNs    int64  `db:"created_ns"`
	LastAccessNs int64  `db:"last_access_ns"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.db.ExecContext(ctx, insertChunk,
		arg.ID,
		arg.LogicalLen,
		arg.StoredLen,
		arg.CompAlgo,
		arg.CreatedNs,
		arg.LastAccessNs,
	)
	return err
}

const listChunkIDs = `-- name: ListChunkIDs :many
SELECT id FROM chunks
`

func (q *Queries) ListChunkIDs(ctx context.Context) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listChunkIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var id []byte
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
