// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: image.proto

package voilapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageManifest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ImageRef                string                 `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"` // "python:3.13" or hash
	ImageDigest             []byte                 `protobuf:"bytes,2,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	ConfigChunk             []byte                 `protobuf:"bytes,3,opt,name=config_chunk,json=configChunk,proto3" json:"config_chunk,omitempty"`                                         // original OCI config.json stored as a chunk
	MergedRootManifestChunk []byte                 `protobuf:"bytes,4,opt,name=merged_root_manifest_chunk,json=mergedRootManifestChunk,proto3" json:"merged_root_manifest_chunk,omitempty"` // what the mount daemon walks
	ProvenanceLayers        []*Layer               `protobuf:"bytes,5,rep,name=provenance_layers,json=provenanceLayers,proto3" json:"provenance_layers,omitempty"`                          // lower -> upper, kept for debug
	TotalSize               uint64                 `protobuf:"varint,6,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`                                              // ingest bytes-in (feeds fetch-stats %)
	ChunkCount              uint64                 `protobuf:"varint,7,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`                                           // ingest chunk count (feeds fetch-stats %)
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ImageManifest) Reset() {
	*x = ImageManifest{}
	mi := &file_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageManifest) ProtoMessage() {}

func (x *ImageManifest) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageManifest.ProtoReflect.Descriptor instead.
func (*ImageManifest) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{0}
}

func (x *ImageManifest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *ImageManifest) GetImageDigest() []byte {
	if x != nil {
		return x.ImageDigest
	}
	return nil
}

func (x *ImageManifest) GetConfigChunk() []byte {
	if x != nil {
		return x.ConfigChunk
	}
	return nil
}

func (x *ImageManifest) GetMergedRootManifestChunk() []byte {
	if x != nil {
		return x.MergedRootManifestChunk
	}
	return nil
}

func (x *ImageManifest) GetProvenanceLayers() []*Layer {
	if x != nil {
		return x.ProvenanceLayers
	}
	return nil
}

func (x *ImageManifest) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ImageManifest) GetChunkCount() uint64 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

type Layer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RootManifestChunk []byte                 `protobuf:"bytes,1,opt,name=root_manifest_chunk,json=rootManifestChunk,proto3" json:"root_manifest_chunk,omitempty"`
	WhiteoutsCount    uint64                 `protobuf:"varint,2,opt,name=whiteouts_count,json=whiteoutsCount,proto3" json:"whiteouts_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Layer) Reset() {
	*x = Layer{}
	mi := &file_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_image_proto_rawDescGZIP(), []int{1}
}

func (x *Layer) GetRootManifestChunk() []byte {
	if x != nil {
		return x.RootManifestChunk
	}
	return nil
}

func (x *Layer) GetWhiteoutsCount() uint64 {
	if x != nil {
		return x.WhiteoutsCount
	}
	return 0
}

var File_image_proto protoreflect.FileDescriptor

const file_image_proto_rawDesc = "" +
	"\n" +
	"\vimage.proto\x12\bvoila.v1\"\xad\x02\n" +
	"\rImageManifest\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\x12!\n" +
	"\fimage_digest\x18\x02 \x01(\fR\vimageDigest\x12!\n" +
	"\fconfig_chunk\x18\x03 \x01(\fR\vconfigChunk\x12;\n" +
	"\x1amerged_root_manifest_chunk\x18\x04 \x01(\fR\x17mergedRootManifestChunk\x12<\n" +
	"\x11provenance_layers\x18\x05 \x03(\v2\x0f.voila.v1.LayerR\x10provenanceLayers\x12\x1d\n" +
	"\n" +
	"total_size\x18\x06 \x01(\x04R\ttotalSize\x12\x1f\n" +
	"\vchunk_count\x18\a \x01(\x04R\n" +
	"chunkCount\"`\n" +
	"\x05Layer\x12.\n" +
	"\x13root_manifest_chunk\x18\x01 \x01(\fR\x11rootManifestChunk\x12'\n" +
	"\x0fwhiteouts_count\x18\x02 \x01(\x04R\x0ewhiteoutsCountB\x1eZ\x1cvoila/internal/proto;voilapbb\x06proto3"

var (
	file_image_proto_rawDescOnce sync.Once
	file_image_proto_rawDescData []byte
)

func file_image_proto_rawDescGZIP() []byte {
	file_image_proto_rawDescOnce.Do(func() {
		file_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_image_proto_rawDesc), len(file_image_proto_rawDesc)))
	})
	return file_image_proto_rawDescData
}

var file_image_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_image_proto_goTypes = []any{
	(*ImageManifest)(nil), // 0: voila.v1.ImageManifest
	(*Layer)(nil),         // 1: voila.v1.Layer
}
var file_image_proto_depIdxs = []int32{
	1, // 0: voila.v1.ImageManifest.provenance_layers:type_name -> voila.v1.Layer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_image_proto_init() }
func file_image_proto_init() {
	if File_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_image_proto_rawDesc), len(file_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_image_proto_goTypes,
		DependencyIndexes: file_image_proto_depIdxs,
		MessageInfos:      file_image_proto_msgTypes,
	}.Build()
	File_image_proto = out.File
	file_image_proto_goTypes = nil
	file_image_proto_depIdxs = nil
}
