// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: manifest.proto

package voilapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"` // st_mode
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Size          uint64                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"` // explicit logical size (covers sparse tails)
	MtimeNs       uint64                 `protobuf:"varint,6,opt,name=mtime_ns,json=mtimeNs,proto3" json:"mtime_ns,omitempty"`
	Nlink         uint32                 `protobuf:"varint,7,opt,name=nlink,proto3" json:"nlink,omitempty"` // >1 when hardlinked
	Xattrs        map[string][]byte      `protobuf:"bytes,8,rep,name=xattrs,proto3" json:"xattrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Blocks        []*Block               `protobuf:"bytes,9,rep,name=blocks,proto3" json:"blocks,omitempty"` // ordered; sparse holes = len-only Block with empty chunk_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *File) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *File) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *File) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *File) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetMtimeNs() uint64 {
	if x != nil {
		return x.MtimeNs
	}
	return 0
}

func (x *File) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *File) GetXattrs() map[string][]byte {
	if x != nil {
		return x.Xattrs
	}
	return nil
}

func (x *File) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OffsetInFile  uint64                 `protobuf:"varint,1,opt,name=offset_in_file,json=offsetInFile,proto3" json:"offset_in_file,omitempty"` // multiple of 1 MiB
	ChunkId       []byte                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`                   // 32-byte BLAKE3 of raw content (compression is store-internal)
	LogicalLen    uint64                 `protobuf:"varint,3,opt,name=logical_len,json=logicalLen,proto3" json:"logical_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetOffsetInFile() uint64 {
	if x != nil {
		return x.OffsetInFile
	}
	return 0
}

func (x *Block) GetChunkId() []byte {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *Block) GetLogicalLen() uint64 {
	if x != nil {
		return x.LogicalLen
	}
	return 0
}

type Dir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	MtimeNs       uint64                 `protobuf:"varint,5,opt,name=mtime_ns,json=mtimeNs,proto3" json:"mtime_ns,omitempty"`
	Entries       map[string]uint64      `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // name -> child inode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dir) Reset() {
	*x = Dir{}
	mi := &file_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir) ProtoMessage() {}

func (x *Dir) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir.ProtoReflect.Descriptor instead.
func (*Dir) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *Dir) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Dir) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Dir) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Dir) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Dir) GetMtimeNs() uint64 {
	if x != nil {
		return x.MtimeNs
	}
	return 0
}

func (x *Dir) GetEntries() map[string]uint64 {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Symlink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symlink) Reset() {
	*x = Symlink{}
	mi := &file_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symlink) ProtoMessage() {}

func (x *Symlink) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symlink.ProtoReflect.Descriptor instead.
func (*Symlink) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *Symlink) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Symlink) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Symlink) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Symlink) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	RdevMajor     uint32                 `protobuf:"varint,5,opt,name=rdev_major,json=rdevMajor,proto3" json:"rdev_major,omitempty"`
	RdevMinor     uint32                 `protobuf:"varint,6,opt,name=rdev_minor,json=rdevMinor,proto3" json:"rdev_minor,omitempty"`
	IsChar        bool                   `protobuf:"varint,7,opt,name=is_char,json=isChar,proto3" json:"is_char,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_manifest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{4}
}

func (x *Device) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Device) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Device) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Device) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Device) GetRdevMajor() uint32 {
	if x != nil {
		return x.RdevMajor
	}
	return 0
}

func (x *Device) GetRdevMinor() uint32 {
	if x != nil {
		return x.RdevMinor
	}
	return 0
}

func (x *Device) GetIsChar() bool {
	if x != nil {
		return x.IsChar
	}
	return false
}

// Hardlink is a SYMBOLIC cross-layer hardlink, present only in per-layer
// provenance manifests (which must be pure functions of their layer tar; the
// link target may live in a lower layer this manifest cannot see). Merged
// manifests never contain Hardlink entries — the merge resolves them to
// shared inodes (two Dir entries pointing at one File).
type Hardlink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	TargetPath    string                 `protobuf:"bytes,2,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"` // cleaned path, relative to rootfs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hardlink) Reset() {
	*x = Hardlink{}
	mi := &file_manifest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hardlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hardlink) ProtoMessage() {}

func (x *Hardlink) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hardlink.ProtoReflect.Descriptor instead.
func (*Hardlink) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{5}
}

func (x *Hardlink) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Hardlink) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type Manifest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Dirs             []*Dir                 `protobuf:"bytes,1,rep,name=dirs,proto3" json:"dirs,omitempty"`
	Files            map[uint64]*File       `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Symlinks         map[uint64]*Symlink    `protobuf:"bytes,3,rep,name=symlinks,proto3" json:"symlinks,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Devices          map[uint64]*Device     `protobuf:"bytes,4,rep,name=devices,proto3" json:"devices,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExternalSubtrees map[uint64][]byte      `protobuf:"bytes,5,rep,name=external_subtrees,json=externalSubtrees,proto3" json:"external_subtrees,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // dir inode -> chunk ID of child Manifest
	Hardlinks        map[uint64]*Hardlink   `protobuf:"bytes,6,rep,name=hardlinks,proto3" json:"hardlinks,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                                       // per-layer manifests only; empty in merged
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_manifest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{6}
}

func (x *Manifest) GetDirs() []*Dir {
	if x != nil {
		return x.Dirs
	}
	return nil
}

func (x *Manifest) GetFiles() map[uint64]*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Manifest) GetSymlinks() map[uint64]*Symlink {
	if x != nil {
		return x.Symlinks
	}
	return nil
}

func (x *Manifest) GetDevices() map[uint64]*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *Manifest) GetExternalSubtrees() map[uint64][]byte {
	if x != nil {
		return x.ExternalSubtrees
	}
	return nil
}

func (x *Manifest) GetHardlinks() map[uint64]*Hardlink {
	if x != nil {
		return x.Hardlinks
	}
	return nil
}

var File_manifest_proto protoreflect.FileDescriptor

const file_manifest_proto_rawDesc = "" +
	"\n" +
	"\x0emanifest.proto\x12\bvoila.v1\"\xb1\x02\n" +
	"\x04File\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\rR\x03gid\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x12\x19\n" +
	"\bmtime_ns\x18\x06 \x01(\x04R\amtimeNs\x12\x14\n" +
	"\x05nlink\x18\a \x01(\rR\x05nlink\x122\n" +
	"\x06xattrs\x18\b \x03(\v2\x1a.voila.v1.File.XattrsEntryR\x06xattrs\x12'\n" +
	"\x06blocks\x18\t \x03(\v2\x0f.voila.v1.BlockR\x06blocks\x1a9\n" +
	"\vXattrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"i\n" +
	"\x05Block\x12$\n" +
	"\x0eoffset_in_file\x18\x01 \x01(\x04R\foffsetInFile\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\fR\achunkId\x12\x1f\n" +
	"\vlogical_len\x18\x03 \x01(\x04R\n" +
	"logicalLen\"\xe0\x01\n" +
	"\x03Dir\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\rR\x03gid\x12\x19\n" +
	"\bmtime_ns\x18\x05 \x01(\x04R\amtimeNs\x124\n" +
	"\aentries\x18\x06 \x03(\v2\x1a.voila.v1.Dir.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"[\n" +
	"\aSymlink\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\rR\x03gid\"\xad\x01\n" +
	"\x06Device\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\rR\x03gid\x12\x1d\n" +
	"\n" +
	"rdev_major\x18\x05 \x01(\rR\trdevMajor\x12\x1d\n" +
	"\n" +
	"rdev_minor\x18\x06 \x01(\rR\trdevMinor\x12\x17\n" +
	"\ais_char\x18\a \x01(\bR\x06isChar\"A\n" +
	"\bHardlink\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x1f\n" +
	"\vtarget_path\x18\x02 \x01(\tR\n" +
	"targetPath\"\xf2\x05\n" +
	"\bManifest\x12!\n" +
	"\x04dirs\x18\x01 \x03(\v2\r.voila.v1.DirR\x04dirs\x123\n" +
	"\x05files\x18\x02 \x03(\v2\x1d.voila.v1.Manifest.FilesEntryR\x05files\x12<\n" +
	"\bsymlinks\x18\x03 \x03(\v2 .voila.v1.Manifest.SymlinksEntryR\bsymlinks\x129\n" +
	"\adevices\x18\x04 \x03(\v2\x1f.voila.v1.Manifest.DevicesEntryR\adevices\x12U\n" +
	"\x11external_subtrees\x18\x05 \x03(\v2(.voila.v1.Manifest.ExternalSubtreesEntryR\x10externalSubtrees\x12?\n" +
	"\thardlinks\x18\x06 \x03(\v2!.voila.v1.Manifest.HardlinksEntryR\thardlinks\x1aH\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.voila.v1.FileR\x05value:\x028\x01\x1aN\n" +
	"\rSymlinksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.voila.v1.SymlinkR\x05value:\x028\x01\x1aL\n" +
	"\fDevicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.voila.v1.DeviceR\x05value:\x028\x01\x1aC\n" +
	"\x15ExternalSubtreesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1aP\n" +
	"\x0eHardlinksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.voila.v1.HardlinkR\x05value:\x028\x01B\x1eZ\x1cvoila/internal/proto;voilapbb\x06proto3"

var (
	file_manifest_proto_rawDescOnce sync.Once
	file_manifest_proto_rawDescData []byte
)

func file_manifest_proto_rawDescGZIP() []byte {
	file_manifest_proto_rawDescOnce.Do(func() {
		file_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manifest_proto_rawDesc), len(file_manifest_proto_rawDesc)))
	})
	return file_manifest_proto_rawDescData
}

var file_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_manifest_proto_goTypes = []any{
	(*File)(nil),     // 0: voila.v1.File
	(*Block)(nil),    // 1: voila.v1.Block
	(*Dir)(nil),      // 2: voila.v1.Dir
	(*Symlink)(nil),  // 3: voila.v1.Symlink
	(*Device)(nil),   // 4: voila.v1.Device
	(*Hardlink)(nil), // 5: voila.v1.Hardlink
	(*Manifest)(nil), // 6: voila.v1.Manifest
	nil,              // 7: voila.v1.File.XattrsEntry
	nil,              // 8: voila.v1.Dir.EntriesEntry
	nil,              // 9: voila.v1.Manifest.FilesEntry
	nil,              // 10: voila.v1.Manifest.SymlinksEntry
	nil,              // 11: voila.v1.Manifest.DevicesEntry
	nil,              // 12: voila.v1.Manifest.ExternalSubtreesEntry
	nil,              // 13: voila.v1.Manifest.HardlinksEntry
}
var file_manifest_proto_depIdxs = []int32{
	7,  // 0: voila.v1.File.xattrs:type_name -> voila.v1.File.XattrsEntry
	1,  // 1: voila.v1.File.blocks:type_name -> voila.v1.Block
	8,  // 2: voila.v1.Dir.entries:type_name -> voila.v1.Dir.EntriesEntry
	2,  // 3: voila.v1.Manifest.dirs:type_name -> voila.v1.Dir
	9,  // 4: voila.v1.Manifest.files:type_name -> voila.v1.Manifest.FilesEntry
	10, // 5: voila.v1.Manifest.symlinks:type_name -> voila.v1.Manifest.SymlinksEntry
	11, // 6: voila.v1.Manifest.devices:type_name -> voila.v1.Manifest.DevicesEntry
	12, // 7: voila.v1.Manifest.external_subtrees:type_name -> voila.v1.Manifest.ExternalSubtreesEntry
	13, // 8: voila.v1.Manifest.hardlinks:type_name -> voila.v1.Manifest.HardlinksEntry
	0,  // 9: voila.v1.Manifest.FilesEntry.value:type_name -> voila.v1.File
	3,  // 10: voila.v1.Manifest.SymlinksEntry.value:type_name -> voila.v1.Symlink
	4,  // 11: voila.v1.Manifest.DevicesEntry.value:type_name -> voila.v1.Device
	5,  // 12: voila.v1.Manifest.HardlinksEntry.value:type_name -> voila.v1.Hardlink
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_manifest_proto_init() }
func file_manifest_proto_init() {
	if File_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manifest_proto_rawDesc), len(file_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manifest_proto_goTypes,
		DependencyIndexes: file_manifest_proto_depIdxs,
		MessageInfos:      file_manifest_proto_msgTypes,
	}.Build()
	File_manifest_proto = out.File
	file_manifest_proto_goTypes = nil
	file_manifest_proto_depIdxs = nil
}
