// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: worker.proto

package voilapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Worker_Run_FullMethodName         = "/voila.v1.Worker/Run"
	Worker_Exec_FullMethodName        = "/voila.v1.Worker/Exec"
	Worker_Events_FullMethodName      = "/voila.v1.Worker/Events"
	Worker_Logs_FullMethodName        = "/voila.v1.Worker/Logs"
	Worker_List_FullMethodName        = "/voila.v1.Worker/List"
	Worker_Kill_FullMethodName        = "/voila.v1.Worker/Kill"
	Worker_SetRegistry_FullMethodName = "/voila.v1.Worker/SetRegistry"
	Worker_BuildRun_FullMethodName    = "/voila.v1.Worker/BuildRun"
)

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Worker is the daemon-side control/IO surface (plan §8). v0.1 serves it over
// a local Unix-domain socket; Phase 3 exposes the same service over TCP+TLS.
type WorkerClient interface {
	// Run launches a context. First client message MUST be RunSpec; subsequent
	// messages carry stdin. First server message is the context id; then
	// stdout/stderr data; the final message is the exit code.
	Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunInput, RunOutput], error)
	// Exec starts an additional process in a running context. Same message
	// discipline as Run.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error)
	// Events streams lifecycle transitions. Clients subscribe, never poll.
	Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Logs replays the context's ring buffer and (optionally) follows.
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error)
	// SetRegistry hands registry URL + bearer token from the CLI to the daemon.
	// The CLI calls this over the local socket (and persists the same values to
	// <root>/registry.creds) so voilad can lazy-fetch and auto-pull without
	// $VOILA_REGISTRY_TOKEN in the daemon's environment.
	SetRegistry(ctx context.Context, in *SetRegistryRequest, opts ...grpc.CallOption) (*SetRegistryResponse, error)
	// BuildRun executes one Dockerfile RUN step: mounts the parent image with a
	// writable overlay, runs argv in a throwaway container, snapshots the overlay
	// upper into a layer manifest chunk, and returns it. First client message
	// MUST be BuildRunSpec; stdout/stderr stream back; terminal message carries
	// exit_code and (on success) layer_manifest_chunk.
	BuildRun(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BuildRunInput, BuildRunOutput], error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunInput, RunOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[0], Worker_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunInput, RunOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_RunClient = grpc.BidiStreamingClient[RunInput, RunOutput]

func (c *workerClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[1], Worker_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecInput, ExecOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_ExecClient = grpc.BidiStreamingClient[ExecInput, ExecOutput]

func (c *workerClient) Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[2], Worker_Events_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_EventsClient = grpc.ServerStreamingClient[Event]

func (c *workerClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[3], Worker_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_LogsClient = grpc.ServerStreamingClient[LogChunk]

func (c *workerClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, Worker_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, Worker_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) SetRegistry(ctx context.Context, in *SetRegistryRequest, opts ...grpc.CallOption) (*SetRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRegistryResponse)
	err := c.cc.Invoke(ctx, Worker_SetRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) BuildRun(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BuildRunInput, BuildRunOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[4], Worker_BuildRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BuildRunInput, BuildRunOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_BuildRunClient = grpc.BidiStreamingClient[BuildRunInput, BuildRunOutput]

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility.
//
// Worker is the daemon-side control/IO surface (plan §8). v0.1 serves it over
// a local Unix-domain socket; Phase 3 exposes the same service over TCP+TLS.
type WorkerServer interface {
	// Run launches a context. First client message MUST be RunSpec; subsequent
	// messages carry stdin. First server message is the context id; then
	// stdout/stderr data; the final message is the exit code.
	Run(grpc.BidiStreamingServer[RunInput, RunOutput]) error
	// Exec starts an additional process in a running context. Same message
	// discipline as Run.
	Exec(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error
	// Events streams lifecycle transitions. Clients subscribe, never poll.
	Events(*EventsRequest, grpc.ServerStreamingServer[Event]) error
	// Logs replays the context's ring buffer and (optionally) follows.
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	List(context.Context, *ListRequest) (*ListResponse, error)
	Kill(context.Context, *KillRequest) (*KillResponse, error)
	// SetRegistry hands registry URL + bearer token from the CLI to the daemon.
	// The CLI calls this over the local socket (and persists the same values to
	// <root>/registry.creds) so voilad can lazy-fetch and auto-pull without
	// $VOILA_REGISTRY_TOKEN in the daemon's environment.
	SetRegistry(context.Context, *SetRegistryRequest) (*SetRegistryResponse, error)
	// BuildRun executes one Dockerfile RUN step: mounts the parent image with a
	// writable overlay, runs argv in a throwaway container, snapshots the overlay
	// upper into a layer manifest chunk, and returns it. First client message
	// MUST be BuildRunSpec; stdout/stderr stream back; terminal message carries
	// exit_code and (on success) layer_manifest_chunk.
	BuildRun(grpc.BidiStreamingServer[BuildRunInput, BuildRunOutput]) error
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServer struct{}

func (UnimplementedWorkerServer) Run(grpc.BidiStreamingServer[RunInput, RunOutput]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedWorkerServer) Exec(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedWorkerServer) Events(*EventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedWorkerServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedWorkerServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedWorkerServer) Kill(context.Context, *KillRequest) (*KillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedWorkerServer) SetRegistry(context.Context, *SetRegistryRequest) (*SetRegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRegistry not implemented")
}
func (UnimplementedWorkerServer) BuildRun(grpc.BidiStreamingServer[BuildRunInput, BuildRunOutput]) error {
	return status.Error(codes.Unimplemented, "method BuildRun not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}
func (UnimplementedWorkerServer) testEmbeddedByValue()                {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	// If the following call panics, it indicates UnimplementedWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).Run(&grpc.GenericServerStream[RunInput, RunOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_RunServer = grpc.BidiStreamingServer[RunInput, RunOutput]

func _Worker_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).Exec(&grpc.GenericServerStream[ExecInput, ExecOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_ExecServer = grpc.BidiStreamingServer[ExecInput, ExecOutput]

func _Worker_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServer).Events(m, &grpc.GenericServerStream[EventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_EventsServer = grpc.ServerStreamingServer[Event]

func _Worker_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_LogsServer = grpc.ServerStreamingServer[LogChunk]

func _Worker_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_SetRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).SetRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_SetRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).SetRegistry(ctx, req.(*SetRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_BuildRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).BuildRun(&grpc.GenericServerStream[BuildRunInput, BuildRunOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Worker_BuildRunServer = grpc.BidiStreamingServer[BuildRunInput, BuildRunOutput]

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voila.v1.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Worker_List_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _Worker_Kill_Handler,
		},
		{
			MethodName: "SetRegistry",
			Handler:    _Worker_SetRegistry_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _Worker_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _Worker_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Events",
			Handler:       _Worker_Events_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Logs",
			Handler:       _Worker_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BuildRun",
			Handler:       _Worker_BuildRun_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "worker.proto",
}
