// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: worker.proto

package voilapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_SCHEDULED   EventType = 1
	EventType_EVENT_TYPE_STARTED     EventType = 2
	EventType_EVENT_TYPE_READY       EventType = 3 // reserved; not emitted in v0.1
	EventType_EVENT_TYPE_FINISHED    EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_SCHEDULED",
		2: "EVENT_TYPE_STARTED",
		3: "EVENT_TYPE_READY",
		4: "EVENT_TYPE_FINISHED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_SCHEDULED":   1,
		"EVENT_TYPE_STARTED":     2,
		"EVENT_TYPE_READY":       3,
		"EVENT_TYPE_FINISHED":    4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

type RunSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Image            string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`                                                  // ref or unique digest prefix
	Args             []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`                                                    // argv override; empty = image entrypoint/cmd
	MemoryLimitBytes int64                  `protobuf:"varint,3,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"` // 0 = unlimited
	CpuQuotaPercent  int32                  `protobuf:"varint,4,opt,name=cpu_quota_percent,json=cpuQuotaPercent,proto3" json:"cpu_quota_percent,omitempty"`    // 100 = one core; 0 = unlimited
	AttachStdin      bool                   `protobuf:"varint,5,opt,name=attach_stdin,json=attachStdin,proto3" json:"attach_stdin,omitempty"`                  // when false the daemon closes stdin immediately
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunSpec) Reset() {
	*x = RunSpec{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSpec) ProtoMessage() {}

func (x *RunSpec) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSpec.ProtoReflect.Descriptor instead.
func (*RunSpec) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RunSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RunSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunSpec) GetMemoryLimitBytes() int64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *RunSpec) GetCpuQuotaPercent() int32 {
	if x != nil {
		return x.CpuQuotaPercent
	}
	return 0
}

func (x *RunSpec) GetAttachStdin() bool {
	if x != nil {
		return x.AttachStdin
	}
	return false
}

type RunInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*RunInput_Spec
	//	*RunInput_Stdin
	//	*RunInput_StdinEof
	Input         isRunInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunInput) Reset() {
	*x = RunInput{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunInput) ProtoMessage() {}

func (x *RunInput) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunInput.ProtoReflect.Descriptor instead.
func (*RunInput) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RunInput) GetInput() isRunInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RunInput) GetSpec() *RunSpec {
	if x != nil {
		if x, ok := x.Input.(*RunInput_Spec); ok {
			return x.Spec
		}
	}
	return nil
}

func (x *RunInput) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Input.(*RunInput_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *RunInput) GetStdinEof() bool {
	if x != nil {
		if x, ok := x.Input.(*RunInput_StdinEof); ok {
			return x.StdinEof
		}
	}
	return false
}

type isRunInput_Input interface {
	isRunInput_Input()
}

type RunInput_Spec struct {
	Spec *RunSpec `protobuf:"bytes,1,opt,name=spec,proto3,oneof"` // required first message
}

type RunInput_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type RunInput_StdinEof struct {
	StdinEof bool `protobuf:"varint,3,opt,name=stdin_eof,json=stdinEof,proto3,oneof"`
}

func (*RunInput_Spec) isRunInput_Input() {}

func (*RunInput_Stdin) isRunInput_Input() {}

func (*RunInput_StdinEof) isRunInput_Input() {}

type RunOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*RunOutput_ContextId
	//	*RunOutput_Stdout
	//	*RunOutput_Stderr
	//	*RunOutput_ExitCode
	//	*RunOutput_Stats
	Output        isRunOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunOutput) Reset() {
	*x = RunOutput{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunOutput) ProtoMessage() {}

func (x *RunOutput) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunOutput.ProtoReflect.Descriptor instead.
func (*RunOutput) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *RunOutput) GetOutput() isRunOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *RunOutput) GetContextId() string {
	if x != nil {
		if x, ok := x.Output.(*RunOutput_ContextId); ok {
			return x.ContextId
		}
	}
	return ""
}

func (x *RunOutput) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Output.(*RunOutput_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *RunOutput) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Output.(*RunOutput_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *RunOutput) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Output.(*RunOutput_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

func (x *RunOutput) GetStats() *FetchStats {
	if x != nil {
		if x, ok := x.Output.(*RunOutput_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

type isRunOutput_Output interface {
	isRunOutput_Output()
}

type RunOutput_ContextId struct {
	ContextId string `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3,oneof"` // always the first message
}

type RunOutput_Stdout struct {
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3,oneof"`
}

type RunOutput_Stderr struct {
	Stderr []byte `protobuf:"bytes,3,opt,name=stderr,proto3,oneof"`
}

type RunOutput_ExitCode struct {
	ExitCode int32 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3,oneof"` // terminal message; stream closes after
}

type RunOutput_Stats struct {
	Stats *FetchStats `protobuf:"bytes,5,opt,name=stats,proto3,oneof"` // sent once, immediately before exit_code
}

func (*RunOutput_ContextId) isRunOutput_Output() {}

func (*RunOutput_Stdout) isRunOutput_Output() {}

func (*RunOutput_Stderr) isRunOutput_Output() {}

func (*RunOutput_ExitCode) isRunOutput_Output() {}

func (*RunOutput_Stats) isRunOutput_Output() {}

// FetchStats reports how much of the image a context actually touched: the
// distinct chunks (manifests + file content) read through the mount's chunk
// store during the run, against the image's ingest totals. In v0.1 fetches
// are local SSD reads; under Phase 1's remote store the same numbers are the
// cold-start network cost — this is the "nothing is fetched unless touched"
// measurement.
type FetchStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunksFetched uint64                 `protobuf:"varint,1,opt,name=chunks_fetched,json=chunksFetched,proto3" json:"chunks_fetched,omitempty"` // distinct chunks read via store.Get
	BytesFetched  uint64                 `protobuf:"varint,2,opt,name=bytes_fetched,json=bytesFetched,proto3" json:"bytes_fetched,omitempty"`    // logical (uncompressed) bytes of those chunks
	ImageChunks   uint64                 `protobuf:"varint,3,opt,name=image_chunks,json=imageChunks,proto3" json:"image_chunks,omitempty"`       // image total from ingest (0 = unknown)
	ImageBytes    uint64                 `protobuf:"varint,4,opt,name=image_bytes,json=imageBytes,proto3" json:"image_bytes,omitempty"`          // image total bytes-in from ingest (0 = unknown)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchStats) Reset() {
	*x = FetchStats{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchStats) ProtoMessage() {}

func (x *FetchStats) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchStats.ProtoReflect.Descriptor instead.
func (*FetchStats) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *FetchStats) GetChunksFetched() uint64 {
	if x != nil {
		return x.ChunksFetched
	}
	return 0
}

func (x *FetchStats) GetBytesFetched() uint64 {
	if x != nil {
		return x.BytesFetched
	}
	return 0
}

func (x *FetchStats) GetImageChunks() uint64 {
	if x != nil {
		return x.ImageChunks
	}
	return 0
}

func (x *FetchStats) GetImageBytes() uint64 {
	if x != nil {
		return x.ImageBytes
	}
	return 0
}

type ExecSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     string                 `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"` // required, non-empty
	AttachStdin   bool                   `protobuf:"varint,3,opt,name=attach_stdin,json=attachStdin,proto3" json:"attach_stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSpec) Reset() {
	*x = ExecSpec{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSpec) ProtoMessage() {}

func (x *ExecSpec) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSpec.ProtoReflect.Descriptor instead.
func (*ExecSpec) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ExecSpec) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *ExecSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecSpec) GetAttachStdin() bool {
	if x != nil {
		return x.AttachStdin
	}
	return false
}

type ExecInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*ExecInput_Spec
	//	*ExecInput_Stdin
	//	*ExecInput_StdinEof
	Input         isExecInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecInput) Reset() {
	*x = ExecInput{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecInput) ProtoMessage() {}

func (x *ExecInput) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecInput.ProtoReflect.Descriptor instead.
func (*ExecInput) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ExecInput) GetInput() isExecInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecInput) GetSpec() *ExecSpec {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_Spec); ok {
			return x.Spec
		}
	}
	return nil
}

func (x *ExecInput) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecInput) GetStdinEof() bool {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_StdinEof); ok {
			return x.StdinEof
		}
	}
	return false
}

type isExecInput_Input interface {
	isExecInput_Input()
}

type ExecInput_Spec struct {
	Spec *ExecSpec `protobuf:"bytes,1,opt,name=spec,proto3,oneof"` // required first message
}

type ExecInput_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecInput_StdinEof struct {
	StdinEof bool `protobuf:"varint,3,opt,name=stdin_eof,json=stdinEof,proto3,oneof"`
}

func (*ExecInput_Spec) isExecInput_Input() {}

func (*ExecInput_Stdin) isExecInput_Input() {}

func (*ExecInput_StdinEof) isExecInput_Input() {}

type ExecOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*ExecOutput_Stdout
	//	*ExecOutput_Stderr
	//	*ExecOutput_ExitCode
	Output        isExecOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *ExecOutput) GetOutput() isExecOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecOutput) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Output.(*ExecOutput_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecOutput) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Output.(*ExecOutput_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecOutput) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Output.(*ExecOutput_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isExecOutput_Output interface {
	isExecOutput_Output()
}

type ExecOutput_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecOutput_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecOutput_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"` // terminal message
}

func (*ExecOutput_Stdout) isExecOutput_Output() {}

func (*ExecOutput_Stderr) isExecOutput_Output() {}

func (*ExecOutput_ExitCode) isExecOutput_Output() {}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     string                 `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Type          EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=voila.v1.EventType" json:"type,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // set on FINISHED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Event) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type EventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     string                 `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"` // empty = all contexts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *EventsRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     string                 `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"` // after replay, stream new chunks until ctx finishes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *LogsRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Stderr        bool                   `protobuf:"varint,2,opt,name=stderr,proto3" json:"stderr,omitempty"` // false = stdout
	TimestampNs   int64                  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetStderr() bool {
	if x != nil {
		return x.Stderr
	}
	return false
}

func (x *LogChunk) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

type ContextInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageRef      string                 `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // scheduled | running | finished
	StartedNs     int64                  `protobuf:"varint,4,opt,name=started_ns,json=startedNs,proto3" json:"started_ns,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`                           // container init pid, 0 unless running
	ExitCode      int32                  `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // valid when finished
	Stats         *FetchStats            `protobuf:"bytes,7,opt,name=stats,proto3" json:"stats,omitempty"`                        // live fetch counters (running) or final (finished)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextInfo) Reset() {
	*x = ContextInfo{}
	mi := &file_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextInfo) ProtoMessage() {}

func (x *ContextInfo) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextInfo.ProtoReflect.Descriptor instead.
func (*ContextInfo) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{12}
}

func (x *ContextInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContextInfo) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *ContextInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContextInfo) GetStartedNs() int64 {
	if x != nil {
		return x.StartedNs
	}
	return 0
}

func (x *ContextInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ContextInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContextInfo) GetStats() *FetchStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contexts      []*ContextInfo         `protobuf:"bytes,1,rep,name=contexts,proto3" json:"contexts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{13}
}

func (x *ListResponse) GetContexts() []*ContextInfo {
	if x != nil {
		return x.Contexts
	}
	return nil
}

type KillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     string                 `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Signal        int32                  `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"` // 0 = SIGTERM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{14}
}

func (x *KillRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *KillRequest) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_worker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{15}
}

type SetRegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegistryUrl   string                 `protobuf:"bytes,1,opt,name=registry_url,json=registryUrl,proto3" json:"registry_url,omitempty"` // registry base URL (e.g. https://host/registry)
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                // bearer API key; empty for public-only reads
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRegistryRequest) Reset() {
	*x = SetRegistryRequest{}
	mi := &file_worker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRegistryRequest) ProtoMessage() {}

func (x *SetRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRegistryRequest.ProtoReflect.Descriptor instead.
func (*SetRegistryRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{16}
}

func (x *SetRegistryRequest) GetRegistryUrl() string {
	if x != nil {
		return x.RegistryUrl
	}
	return ""
}

func (x *SetRegistryRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SetRegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRegistryResponse) Reset() {
	*x = SetRegistryResponse{}
	mi := &file_worker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRegistryResponse) ProtoMessage() {}

func (x *SetRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRegistryResponse.ProtoReflect.Descriptor instead.
func (*SetRegistryResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{17}
}

type BuildRunSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootChunk     []byte                 `protobuf:"bytes,1,opt,name=root_chunk,json=rootChunk,proto3" json:"root_chunk,omitempty"`       // parent merged-root manifest chunk
	ConfigChunk   []byte                 `protobuf:"bytes,2,opt,name=config_chunk,json=configChunk,proto3" json:"config_chunk,omitempty"` // OCI image config chunk
	Argv          []string               `protobuf:"bytes,3,rep,name=argv,proto3" json:"argv,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	Cwd           string                 `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	User          string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	HostNetwork   bool                   `protobuf:"varint,7,opt,name=host_network,json=hostNetwork,proto3" json:"host_network,omitempty"` // default true for build RUN (apt-get, curl, …)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRunSpec) Reset() {
	*x = BuildRunSpec{}
	mi := &file_worker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRunSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRunSpec) ProtoMessage() {}

func (x *BuildRunSpec) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRunSpec.ProtoReflect.Descriptor instead.
func (*BuildRunSpec) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{18}
}

func (x *BuildRunSpec) GetRootChunk() []byte {
	if x != nil {
		return x.RootChunk
	}
	return nil
}

func (x *BuildRunSpec) GetConfigChunk() []byte {
	if x != nil {
		return x.ConfigChunk
	}
	return nil
}

func (x *BuildRunSpec) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *BuildRunSpec) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *BuildRunSpec) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *BuildRunSpec) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *BuildRunSpec) GetHostNetwork() bool {
	if x != nil {
		return x.HostNetwork
	}
	return false
}

type BuildRunInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*BuildRunInput_Spec
	//	*BuildRunInput_Stdin
	//	*BuildRunInput_StdinEof
	Input         isBuildRunInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRunInput) Reset() {
	*x = BuildRunInput{}
	mi := &file_worker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRunInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRunInput) ProtoMessage() {}

func (x *BuildRunInput) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRunInput.ProtoReflect.Descriptor instead.
func (*BuildRunInput) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{19}
}

func (x *BuildRunInput) GetInput() isBuildRunInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *BuildRunInput) GetSpec() *BuildRunSpec {
	if x != nil {
		if x, ok := x.Input.(*BuildRunInput_Spec); ok {
			return x.Spec
		}
	}
	return nil
}

func (x *BuildRunInput) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Input.(*BuildRunInput_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *BuildRunInput) GetStdinEof() bool {
	if x != nil {
		if x, ok := x.Input.(*BuildRunInput_StdinEof); ok {
			return x.StdinEof
		}
	}
	return false
}

type isBuildRunInput_Input interface {
	isBuildRunInput_Input()
}

type BuildRunInput_Spec struct {
	Spec *BuildRunSpec `protobuf:"bytes,1,opt,name=spec,proto3,oneof"`
}

type BuildRunInput_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type BuildRunInput_StdinEof struct {
	StdinEof bool `protobuf:"varint,3,opt,name=stdin_eof,json=stdinEof,proto3,oneof"`
}

func (*BuildRunInput_Spec) isBuildRunInput_Input() {}

func (*BuildRunInput_Stdin) isBuildRunInput_Input() {}

func (*BuildRunInput_StdinEof) isBuildRunInput_Input() {}

type BuildRunOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*BuildRunOutput_Stdout
	//	*BuildRunOutput_Stderr
	//	*BuildRunOutput_ExitCode
	//	*BuildRunOutput_LayerManifestChunk
	Output        isBuildRunOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRunOutput) Reset() {
	*x = BuildRunOutput{}
	mi := &file_worker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRunOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRunOutput) ProtoMessage() {}

func (x *BuildRunOutput) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRunOutput.ProtoReflect.Descriptor instead.
func (*BuildRunOutput) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{20}
}

func (x *BuildRunOutput) GetOutput() isBuildRunOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *BuildRunOutput) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Output.(*BuildRunOutput_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *BuildRunOutput) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Output.(*BuildRunOutput_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *BuildRunOutput) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Output.(*BuildRunOutput_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

func (x *BuildRunOutput) GetLayerManifestChunk() []byte {
	if x != nil {
		if x, ok := x.Output.(*BuildRunOutput_LayerManifestChunk); ok {
			return x.LayerManifestChunk
		}
	}
	return nil
}

type isBuildRunOutput_Output interface {
	isBuildRunOutput_Output()
}

type BuildRunOutput_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type BuildRunOutput_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type BuildRunOutput_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

type BuildRunOutput_LayerManifestChunk struct {
	LayerManifestChunk []byte `protobuf:"bytes,4,opt,name=layer_manifest_chunk,json=layerManifestChunk,proto3,oneof"` // set on success before exit_code
}

func (*BuildRunOutput_Stdout) isBuildRunOutput_Output() {}

func (*BuildRunOutput_Stderr) isBuildRunOutput_Output() {}

func (*BuildRunOutput_ExitCode) isBuildRunOutput_Output() {}

func (*BuildRunOutput_LayerManifestChunk) isBuildRunOutput_Output() {}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\bvoila.v1\"\xb0\x01\n" +
	"\aRunSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12,\n" +
	"\x12memory_limit_bytes\x18\x03 \x01(\x03R\x10memoryLimitBytes\x12*\n" +
	"\x11cpu_quota_percent\x18\x04 \x01(\x05R\x0fcpuQuotaPercent\x12!\n" +
	"\fattach_stdin\x18\x05 \x01(\bR\vattachStdin\"s\n" +
	"\bRunInput\x12'\n" +
	"\x04spec\x18\x01 \x01(\v2\x11.voila.v1.RunSpecH\x00R\x04spec\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12\x1d\n" +
	"\tstdin_eof\x18\x03 \x01(\bH\x00R\bstdinEofB\a\n" +
	"\x05input\"\xb7\x01\n" +
	"\tRunOutput\x12\x1f\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tH\x00R\tcontextId\x12\x18\n" +
	"\x06stdout\x18\x02 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x03 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x04 \x01(\x05H\x00R\bexitCode\x12,\n" +
	"\x05stats\x18\x05 \x01(\v2\x14.voila.v1.FetchStatsH\x00R\x05statsB\b\n" +
	"\x06output\"\x9c\x01\n" +
	"\n" +
	"FetchStats\x12%\n" +
	"\x0echunks_fetched\x18\x01 \x01(\x04R\rchunksFetched\x12#\n" +
	"\rbytes_fetched\x18\x02 \x01(\x04R\fbytesFetched\x12!\n" +
	"\fimage_chunks\x18\x03 \x01(\x04R\vimageChunks\x12\x1f\n" +
	"\vimage_bytes\x18\x04 \x01(\x04R\n" +
	"imageBytes\"`\n" +
	"\bExecSpec\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12!\n" +
	"\fattach_stdin\x18\x03 \x01(\bR\vattachStdin\"u\n" +
	"\tExecInput\x12(\n" +
	"\x04spec\x18\x01 \x01(\v2\x12.voila.v1.ExecSpecH\x00R\x04spec\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12\x1d\n" +
	"\tstdin_eof\x18\x03 \x01(\bH\x00R\bstdinEofB\a\n" +
	"\x05input\"i\n" +
	"\n" +
	"ExecOutput\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCodeB\b\n" +
	"\x06output\"\x8f\x01\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.voila.v1.EventTypeR\x04type\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\".\n" +
	"\rEventsRequest\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\"D\n" +
	"\vLogsRequest\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"Y\n" +
	"\bLogChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\bR\x06stderr\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x03R\vtimestampNs\"\r\n" +
	"\vListRequest\"\xcc\x01\n" +
	"\vContextInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\timage_ref\x18\x02 \x01(\tR\bimageRef\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_ns\x18\x04 \x01(\x03R\tstartedNs\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12\x1b\n" +
	"\texit_code\x18\x06 \x01(\x05R\bexitCode\x12*\n" +
	"\x05stats\x18\a \x01(\v2\x14.voila.v1.FetchStatsR\x05stats\"A\n" +
	"\fListResponse\x121\n" +
	"\bcontexts\x18\x01 \x03(\v2\x15.voila.v1.ContextInfoR\bcontexts\"D\n" +
	"\vKillRequest\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\"\x0e\n" +
	"\fKillResponse\"M\n" +
	"\x12SetRegistryRequest\x12!\n" +
	"\fregistry_url\x18\x01 \x01(\tR\vregistryUrl\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x15\n" +
	"\x13SetRegistryResponse\"\xbf\x01\n" +
	"\fBuildRunSpec\x12\x1d\n" +
	"\n" +
	"root_chunk\x18\x01 \x01(\fR\trootChunk\x12!\n" +
	"\fconfig_chunk\x18\x02 \x01(\fR\vconfigChunk\x12\x12\n" +
	"\x04argv\x18\x03 \x03(\tR\x04argv\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12!\n" +
	"\fhost_network\x18\a \x01(\bR\vhostNetwork\"}\n" +
	"\rBuildRunInput\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x16.voila.v1.BuildRunSpecH\x00R\x04spec\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12\x1d\n" +
	"\tstdin_eof\x18\x03 \x01(\bH\x00R\bstdinEofB\a\n" +
	"\x05input\"\xa1\x01\n" +
	"\x0eBuildRunOutput\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCode\x122\n" +
	"\x14layer_manifest_chunk\x18\x04 \x01(\fH\x00R\x12layerManifestChunkB\b\n" +
	"\x06output*\x88\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14EVENT_TYPE_SCHEDULED\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_STARTED\x10\x02\x12\x14\n" +
	"\x10EVENT_TYPE_READY\x10\x03\x12\x17\n" +
	"\x13EVENT_TYPE_FINISHED\x10\x042\xdb\x03\n" +
	"\x06Worker\x122\n" +
	"\x03Run\x12\x12.voila.v1.RunInput\x1a\x13.voila.v1.RunOutput(\x010\x01\x125\n" +
	"\x04Exec\x12\x13.voila.v1.ExecInput\x1a\x14.voila.v1.ExecOutput(\x010\x01\x124\n" +
	"\x06Events\x12\x17.voila.v1.EventsRequest\x1a\x0f.voila.v1.Event0\x01\x123\n" +
	"\x04Logs\x12\x15.voila.v1.LogsRequest\x1a\x12.voila.v1.LogChunk0\x01\x125\n" +
	"\x04List\x12\x15.voila.v1.ListRequest\x1a\x16.voila.v1.ListResponse\x125\n" +
	"\x04Kill\x12\x15.voila.v1.KillRequest\x1a\x16.voila.v1.KillResponse\x12J\n" +
	"\vSetRegistry\x12\x1c.voila.v1.SetRegistryRequest\x1a\x1d.voila.v1.SetRegistryResponse\x12A\n" +
	"\bBuildRun\x12\x17.voila.v1.BuildRunInput\x1a\x18.voila.v1.BuildRunOutput(\x010\x01B\x1eZ\x1cvoila/internal/proto;voilapbb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_worker_proto_goTypes = []any{
	(EventType)(0),              // 0: voila.v1.EventType
	(*RunSpec)(nil),             // 1: voila.v1.RunSpec
	(*RunInput)(nil),            // 2: voila.v1.RunInput
	(*RunOutput)(nil),           // 3: voila.v1.RunOutput
	(*FetchStats)(nil),          // 4: voila.v1.FetchStats
	(*ExecSpec)(nil),            // 5: voila.v1.ExecSpec
	(*ExecInput)(nil),           // 6: voila.v1.ExecInput
	(*ExecOutput)(nil),          // 7: voila.v1.ExecOutput
	(*Event)(nil),               // 8: voila.v1.Event
	(*EventsRequest)(nil),       // 9: voila.v1.EventsRequest
	(*LogsRequest)(nil),         // 10: voila.v1.LogsRequest
	(*LogChunk)(nil),            // 11: voila.v1.LogChunk
	(*ListRequest)(nil),         // 12: voila.v1.ListRequest
	(*ContextInfo)(nil),         // 13: voila.v1.ContextInfo
	(*ListResponse)(nil),        // 14: voila.v1.ListResponse
	(*KillRequest)(nil),         // 15: voila.v1.KillRequest
	(*KillResponse)(nil),        // 16: voila.v1.KillResponse
	(*SetRegistryRequest)(nil),  // 17: voila.v1.SetRegistryRequest
	(*SetRegistryResponse)(nil), // 18: voila.v1.SetRegistryResponse
	(*BuildRunSpec)(nil),        // 19: voila.v1.BuildRunSpec
	(*BuildRunInput)(nil),       // 20: voila.v1.BuildRunInput
	(*BuildRunOutput)(nil),      // 21: voila.v1.BuildRunOutput
}
var file_worker_proto_depIdxs = []int32{
	1,  // 0: voila.v1.RunInput.spec:type_name -> voila.v1.RunSpec
	4,  // 1: voila.v1.RunOutput.stats:type_name -> voila.v1.FetchStats
	5,  // 2: voila.v1.ExecInput.spec:type_name -> voila.v1.ExecSpec
	0,  // 3: voila.v1.Event.type:type_name -> voila.v1.EventType
	4,  // 4: voila.v1.ContextInfo.stats:type_name -> voila.v1.FetchStats
	13, // 5: voila.v1.ListResponse.contexts:type_name -> voila.v1.ContextInfo
	19, // 6: voila.v1.BuildRunInput.spec:type_name -> voila.v1.BuildRunSpec
	2,  // 7: voila.v1.Worker.Run:input_type -> voila.v1.RunInput
	6,  // 8: voila.v1.Worker.Exec:input_type -> voila.v1.ExecInput
	9,  // 9: voila.v1.Worker.Events:input_type -> voila.v1.EventsRequest
	10, // 10: voila.v1.Worker.Logs:input_type -> voila.v1.LogsRequest
	12, // 11: voila.v1.Worker.List:input_type -> voila.v1.ListRequest
	15, // 12: voila.v1.Worker.Kill:input_type -> voila.v1.KillRequest
	17, // 13: voila.v1.Worker.SetRegistry:input_type -> voila.v1.SetRegistryRequest
	20, // 14: voila.v1.Worker.BuildRun:input_type -> voila.v1.BuildRunInput
	3,  // 15: voila.v1.Worker.Run:output_type -> voila.v1.RunOutput
	7,  // 16: voila.v1.Worker.Exec:output_type -> voila.v1.ExecOutput
	8,  // 17: voila.v1.Worker.Events:output_type -> voila.v1.Event
	11, // 18: voila.v1.Worker.Logs:output_type -> voila.v1.LogChunk
	14, // 19: voila.v1.Worker.List:output_type -> voila.v1.ListResponse
	16, // 20: voila.v1.Worker.Kill:output_type -> voila.v1.KillResponse
	18, // 21: voila.v1.Worker.SetRegistry:output_type -> voila.v1.SetRegistryResponse
	21, // 22: voila.v1.Worker.BuildRun:output_type -> voila.v1.BuildRunOutput
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*RunInput_Spec)(nil),
		(*RunInput_Stdin)(nil),
		(*RunInput_StdinEof)(nil),
	}
	file_worker_proto_msgTypes[2].OneofWrappers = []any{
		(*RunOutput_ContextId)(nil),
		(*RunOutput_Stdout)(nil),
		(*RunOutput_Stderr)(nil),
		(*RunOutput_ExitCode)(nil),
		(*RunOutput_Stats)(nil),
	}
	file_worker_proto_msgTypes[5].OneofWrappers = []any{
		(*ExecInput_Spec)(nil),
		(*ExecInput_Stdin)(nil),
		(*ExecInput_StdinEof)(nil),
	}
	file_worker_proto_msgTypes[6].OneofWrappers = []any{
		(*ExecOutput_Stdout)(nil),
		(*ExecOutput_Stderr)(nil),
		(*ExecOutput_ExitCode)(nil),
	}
	file_worker_proto_msgTypes[19].OneofWrappers = []any{
		(*BuildRunInput_Spec)(nil),
		(*BuildRunInput_Stdin)(nil),
		(*BuildRunInput_StdinEof)(nil),
	}
	file_worker_proto_msgTypes[20].OneofWrappers = []any{
		(*BuildRunOutput_Stdout)(nil),
		(*BuildRunOutput_Stderr)(nil),
		(*BuildRunOutput_ExitCode)(nil),
		(*BuildRunOutput_LayerManifestChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		EnumInfos:         file_worker_proto_enumTypes,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
