// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package imagestore

import ()

type Image struct {
	Ref                     string `db:"ref"`
	ImageDigest             []byte `db:"image_digest"`
	MergedRootManifestChunk []byte `db:"merged_root_manifest_chunk"`
	TotalSize               int64  `db:"total_size"`
	ChunkCount              int64  `db:"chunk_count"`
	IngestedNs              int64  `db:"ingested_ns"`
	LastUsedNs              int64  `db:"last_used_ns"`
}

type Layer struct {
	OciDigest     string `db:"oci_digest"`
	ManifestChunk []byte `db:"manifest_chunk"`
	CreatedNs     int64  `db:"created_ns"`
}
