// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package imagestore

import (
	"context"
)

const countLayers = `-- name: CountLayers :one
SELECT COUNT(*) FROM layers
`

func (q *Queries) CountLayers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLayers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE ref = ?
`

func (q *Queries) DeleteImage(ctx context.Context, ref string) error {
	_, err := q.db.ExecContext(ctx, deleteImage, ref)
	return err
}

const deleteLayer = `-- name: DeleteLayer :exec
DELETE FROM layers WHERE oci_digest = ?
`

func (q *Queries) DeleteLayer(ctx context.Context, ociDigest string) error {
	_, err := q.db.ExecContext(ctx, deleteLayer, ociDigest)
	return err
}

const getImageByRef = `-- name: GetImageByRef :one
SELECT ref, image_digest, merged_root_manifest_chunk, total_size, chunk_count, ingested_ns, last_used_ns FROM images WHERE ref = ?
`

func (q *Queries) GetImageByRef(ctx context.Context, ref string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByRef, ref)
	var i Image
	err := row.Scan(
		&i.Ref,
		&i.ImageDigest,
		&i.MergedRootManifestChunk,
		&i.TotalSize,
		&i.ChunkCount,
		&i.IngestedNs,
		&i.LastUsedNs,
	)
	return i, err
}

const getLayerChunk = `-- name: GetLayerChunk :one
SELECT manifest_chunk FROM layers WHERE oci_digest = ?
`

func (q *Queries) GetLayerChunk(ctx context.Context, ociDigest string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getLayerChunk, ociDigest)
	var manifest_chunk []byte
	err := row.Scan(&manifest_chunk)
	return manifest_chunk, err
}

const listImages = `-- name: ListImages :many
SELECT ref, image_digest, merged_root_manifest_chunk, total_size, chunk_count, ingested_ns, last_used_ns FROM images ORDER BY ref ASC
`

func (q *Queries) ListImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.Ref,
			&i.ImageDigest,
			&i.MergedRootManifestChunk,
			&i.TotalSize,
			&i.ChunkCount,
			&i.IngestedNs,
			&i.LastUsedNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLayers = `-- name: ListLayers :many
SELECT oci_digest, manifest_chunk FROM layers
`

type ListLayersRow struct {
	OciDigest     string `db:"oci_digest"`
	ManifestChunk []byte `db:"manifest_chunk"`
}

func (q *Queries) ListLayers(ctx context.Context) ([]ListLayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listLayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLayersRow
	for rows.Next() {
		var i ListLayersRow
		if err := rows.Scan(&i.OciDigest, &i.ManifestChunk); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImage = `-- name: UpsertImage :exec
INSERT INTO images (ref, image_digest, merged_root_manifest_chunk, total_size, chunk_count, ingested_ns, last_used_ns)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(ref) DO UPDATE SET
  image_digest=excluded.image_digest,
  merged_root_manifest_chunk=excluded.merged_root_manifest_chunk,
  total_size=excluded.total_size,
  chunk_count=excluded.chunk_count,
  ingested_ns=excluded.ingested_ns,
  last_used_ns=excluded.last_used_ns
`

type UpsertImageParams struct {
	Ref                     string `db:"ref"`
	ImageDigest             []byte `db:"image_digest"`
	MergedRootManifestChunk []byte `db:"merged_root_manifest_chunk"`
	TotalSize               int64  `db:"total_size"`
	ChunkCount              int64  `db:"chunk_count"`
	IngestedNs              int64  `db:"ingested_ns"`
	LastUsedNs              int64  `db:"last_used_ns"`
}

func (q *Queries) UpsertImage(ctx context.Context, arg UpsertImageParams) error {
	_, err := q.db.ExecContext(ctx, upsertImage,
		arg.Ref,
		arg.ImageDigest,
		arg.MergedRootManifestChunk,
		arg.TotalSize,
		arg.ChunkCount,
		arg.IngestedNs,
		arg.LastUsedNs,
	)
	return err
}

const upsertLayer = `-- name: UpsertLayer :exec
INSERT INTO layers (oci_digest, manifest_chunk, created_ns) VALUES (?, ?, ?)
ON CONFLICT(oci_digest) DO UPDATE SET manifest_chunk=excluded.manifest_chunk
`

type UpsertLayerParams struct {
	OciDigest     string `db:"oci_digest"`
	ManifestChunk []byte `db:"manifest_chunk"`
	CreatedNs     int64  `db:"created_ns"`
}

func (q *Queries) UpsertLayer(ctx context.Context, arg UpsertLayerParams) error {
	_, err := q.db.ExecContext(ctx, upsertLayer, arg.OciDigest, arg.ManifestChunk, arg.CreatedNs)
	return err
}
